package win;
import dao.daoAlmuerzo;
import dao.daoCena;
import dao.daoComedor;
import dao.daoDesayuno;
import entities.Almuerzo;
import entities.Cena;
import entities.Desayuno;
import java.awt.event.KeyEvent;
import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import util.Ticket;

/**
 *
 * @author Jhon
 */
public class winInfo extends javax.swing.JDialog implements Runnable{
    /**
     * Creates new form winInfo
     * @param parent
     * @param modal
     */
    daoComedor daocm;
    daoDesayuno daod;
    daoAlmuerzo daoa;
    daoCena daoc;
    Thread h1;
    String hora,minutos,segundos,ampm,mes,dia;
    int orden,anio;
       
    public winInfo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        h1 = new Thread(this);
        h1.start();
        lblcodigo.setText(winFirmar.cod);
        lbldni.setText(winFirmar.dni);
        lblnom.setText(winFirmar.nom+", "+winFirmar.ape);
        lblfacu.setText(winFirmar.fac);
        lblesc.setText(winFirmar.eap);
        lblbeca.setText(winFirmar.beca);
        String master = System.getProperty("user.dir") + "/fotos/find_user.png";
            try {
                master = URLDecoder.decode(master, "UTF-8");
                panelImage1.setIcon(new ImageIcon(master));
                //this.setIconImage(new ImageIcon(master).getImage());
            } catch (UnsupportedEncodingException ex) {  
                System.out.println(""+ex.getMessage());
            }
            jButton2.requestFocus(true);
            jButton2.setFocusable(true);
            orden = winMenu.moda.getRowCount()+1;
            lblOrden.setText(""+orden);
        daod = new daoDesayuno();
        CalcularFecha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblcodigo = new javax.swing.JLabel();
        lbldni = new javax.swing.JLabel();
        lblnom = new javax.swing.JLabel();
        lblfacu = new javax.swing.JLabel();
        lblesc = new javax.swing.JLabel();
        lblbeca = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        panelImage1 = new javax.swing.JLabel();
        lblOrden = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblh = new javax.swing.JLabel();
        lblestado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Codigo:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("DNI:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Facultad:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Escuela:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Beca:");

        lblcodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcodigo.setText("codigo");

        lbldni.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldni.setText("dni");

        lblnom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnom.setText("nombres");

        lblfacu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblfacu.setText("facultad");

        lblesc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblesc.setText("eap");

        lblbeca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblbeca.setText("tipo de beca");

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Aceptar");
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap())
        );

        panelImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        lblOrden.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOrden.setText("orden");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("N°");

        lblh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblh.setText("Hora");

        lblestado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblestado.setText("Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblcodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbldni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblnom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblfacu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblbeca, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                                    .addComponent(lblestado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblh, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblcodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbldni))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblnom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblfacu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblesc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblbeca)
                            .addComponent(lblOrden)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblh, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblestado)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        for (int i = 0; i < winMenu.moda.getRowCount(); i++) {
            if (winMenu.moda.getValueAt(i, 1).equals(lblcodigo.getText())) {
                JOptionPane.showMessageDialog(null, "Ya se tomo la Asistencia", "Nota", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        int hh,mm,ss,ms,dd;
        hh = Integer.parseInt(hora);
        mm = Integer.parseInt(minutos);
        ss = Integer.parseInt(segundos);
        ms = Integer.parseInt(mes);
        dd = Integer.parseInt(dia);
        //1 hace referencia al id de la tabla comedors
        if (lblestado.getText().equalsIgnoreCase("Desayuno")) {
            Desayuno d = new Desayuno("1",winFirmar.idcm,anio+"/"+ms+"/"+dd+" "+hh+":"+mm+":"+ss);
            daod = new daoDesayuno();
            if (daod.Guardar(d)) {
                winMenu.MostrarAsistencia();
                lblOrden.setText("" + orden);
            } 
        }
        
        if (lblestado.getText().equalsIgnoreCase("Almuerzo")) {
            Almuerzo a = new Almuerzo("1",winFirmar.idcm,anio+"/"+ms+"/"+dd+" "+hh+":"+mm+":"+ss);
            daoa = new daoAlmuerzo();
            if (daoa.Guardar(a)) {
                winMenu.MostrarAsistencia();
                lblOrden.setText("" + orden);
            }
        }
        
        if (lblestado.getText().equalsIgnoreCase("Cena")) {
            Cena c = new Cena("1",winFirmar.idcm,anio+"/"+ms+"/"+dd+" "+hh+":"+mm+":"+ss);
            daoc = new daoCena();
            if (daoc.Guardar(c)) {
                winMenu.MostrarAsistencia();
                lblOrden.setText("" + orden);
            }
        }
        dispose();
        PrintTicket();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyTyped
        char tecla = evt.getKeyChar();
        if (tecla == KeyEvent.VK_ENTER) {
            jButton2.doClick();
        }
    }//GEN-LAST:event_jButton2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(winInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(winInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(winInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(winInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                winInfo dialog = new winInfo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
                }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblOrden;
    public static javax.swing.JLabel lblbeca;
    public static javax.swing.JLabel lblcodigo;
    public static javax.swing.JLabel lbldni;
    public static javax.swing.JLabel lblesc;
    public static javax.swing.JLabel lblestado;
    public static javax.swing.JLabel lblfacu;
    private javax.swing.JLabel lblh;
    public static javax.swing.JLabel lblnom;
    private javax.swing.JLabel panelImage1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void run() {
        Thread ct = Thread.currentThread();
        while (ct == h1) {
            calcula();
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
        }
    }
    public void calcula () {        
        Calendar calendar = new GregorianCalendar();
        Date fechaHoraActual = new Date();
        calendar.setTime(fechaHoraActual);
        ampm = calendar.get(Calendar.AM_PM)==Calendar.AM?"AM":"PM";

        if(ampm.equals("PM")){
            int h = calendar.get(Calendar.HOUR_OF_DAY)-12;
        hora = h>9?""+h:"0"+h;
        }else{
         hora = calendar.get(Calendar.HOUR_OF_DAY)>9?""+calendar.get(Calendar.HOUR_OF_DAY):"0"+calendar.get(Calendar.HOUR_OF_DAY);            
        }
        minutos = calendar.get(Calendar.MINUTE)>9?""+calendar.get(Calendar.MINUTE):"0"+calendar.get(Calendar.MINUTE);
        segundos = calendar.get(Calendar.SECOND)>9?""+calendar.get(Calendar.SECOND):"0"+calendar.get(Calendar.SECOND);
        lblh.setText(hora + ":" + minutos);
        int hh;
        hh = Integer.parseInt(hora);
        if (ampm.equalsIgnoreCase("am")) {
            if (hh<11) {
                lblestado.setText("DESAYUNO");
            }
            if (hh>10) {
                lblestado.setText("ALMUERZO");
            }
        }
        if (ampm.equalsIgnoreCase("pm")) {
            if (hh<5) {
                lblestado.setText("ALMUERZO");
            }
            if (hh>4) {
                lblestado.setText("CENA");
            }
        }
    }    
    private void CalcularFecha() {
        DecimalFormat formato = new DecimalFormat("00");
        Calendar cal = Calendar.getInstance();
        anio = cal.get(Calendar.YEAR);
        mes = formato.format((cal.get(Calendar.MONTH) + 1));
        dia = formato.format(cal.get(Calendar.DATE));
        //String fecha = cal.get(Calendar.YEAR) + "/" + formato.format((cal.get(Calendar.MONTH) + 1)) + "/" + formato.format(cal.get(Calendar.DATE));
    }
   
    private void PrintTicket(){
        Date date = new Date();
        SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat hora = new SimpleDateFormat("hh:mm:ss aa");
        Ticket ticket = new Ticket();
        ticket.AddCabecera("Universidad Nacional");
        ticket.AddCabecera(ticket.DarEspacio());
        ticket.AddCabecera("Hermilio Valdizan");
        ticket.AddCabecera(ticket.DarEspacio());
        ticket.AddCabecera(ticket.DarEspacio());
        ticket.AddCabecera(""+lblestado.getText()+" "+lblOrden.getText());
        ticket.AddCabecera(ticket.DarEspacio());
        ticket.AddCabecera("Escuela: "+lblesc.getText());
        ticket.AddCabecera(ticket.DarEspacio());
        ticket.AddCabecera("Código: "+lblcodigo.getText());
        ticket.AddCabecera(ticket.DarEspacio());
        ticket.AddCabecera("Nombres: "+winFirmar.nom);
        ticket.AddCabecera(ticket.DarEspacio());
        ticket.AddCabecera("Apellidos: "+winFirmar.ape);
        ticket.AddCabecera(ticket.DarEspacio());
        ticket.AddCabecera("Beca: "+lblbeca.getText());
        ticket.AddCabecera(ticket.DarEspacio());
        ticket.AddCabecera(ticket.DibujarLinea(29));
        ticket.AddCabecera(ticket.DarEspacio());
        ticket.AddCabecera(ticket.DarEspacio());
        ticket.AddCabecera(ticket.DarEspacio());
        ticket.AddPieLinea("" + fecha.format(date) + " " + hora.format(date));
        ticket.AddPieLinea(ticket.DarEspacio());
        ticket.AddPieLinea(ticket.DarEspacio());
        ticket.AddPieLinea(ticket.DarEspacio());
        ticket.AddPieLinea(ticket.DarEspacio());
        ticket.AddPieLinea(ticket.DarEspacio());
        try { 
            ticket.ImprimirDocumento();
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(winInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
}
